name: Code Style

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Linter
        run: ruff check --select I --fix
        continue-on-error: true
      - name: Run Formatter
        run: ruff format 
        continue-on-error: true
